spring:
  application:
    name: talentgraph-api

server:
  port: 8080

cognodb:
  uri: ${COGNODB_URI}
  username: ${COGNODB_USERNAME}
  password: ${COGNODB_PASSWORD}
  database: ${COGNODB_DATABASE:}
