spring:
  application:
    name: talentgraph-api
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080

cognodb:
  uri: ${COGNODB_URI}
  username: ${COGNODB_USERNAME}
  password: ${COGNODB_PASSWORD}
  database: ${COGNODB_DATABASE:}
